sudo: true
dist: trusty
language: cpp
os: linux

# Install dependencies
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -y
    - sudo apt-get install gcc-5 g++-5 -y
    # increase priority of gcc5 and g++5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 150 --slave /usr/bin/g++ g++ /usr/bin/g++-5
    # download and install miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    # if we don't create this symlink there is a weird bug in boost because it looks for this specific directory
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy numpy pip matplotlib pandas
    - ln -s $HOME/miniconda/envs/test-environment/include/python3.6m $HOME/miniconda/envs/test-environment/include/python3.6
    - source activate test-environment
    - git clone https://github.com/gf712/AbPyTools
    - cd AbPyTools
    - python setup.py install
    - python setup.py test

install:
    # build package
    - cd -
    - mkdir build
    - cd build
    - cmake -DPYTHON_INCLUDE_DIR=$HOME/miniconda/include/python3.6m -DPYTHON_LIBRARY=$HOME/miniconda/lib/libpython3.6m.so ..
    - make

# Run tests
script:
    - env CTEST_OUTPUT_ON_FAILURE=1 make
