sudo: true
dist: trusty
language: cpp
os: linux

addons:
  apt:
    packages:
      - cmake
      - libgles2-mesa-dev
      - libxrender-dev
      - libfreetype6-dev
      - libx11-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxcb1-dev
      - libx11-xcb-dev

# Install dependencies
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -y
    - sudo apt-get install gcc-5 g++-5 
    # increase priority of gcc5 and g++5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 150 --slave /usr/bin/g++ g++ /usr/bin/g++-5
    # https://github.com/filipwasil/fillwave/issues/58
#    - git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake ../glfw && make -j4 && sudo make install && cd $HOME
    # download and install miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    # if we don't create this symlink there is a weird bug in boost because it looks for this specific directory
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy numpy pip matplotlib pandas
    - ln -s $HOME/miniconda/envs/test-environment/include/python3.6m $HOME/miniconda/envs/test-environment/include/python3.6
    - source activate test-environment
    - git clone https://github.com/gf712/AbPyTools
    - cd AbPyTools
    - python setup.py install
    - python setup.py test

install:
    # build package
    - cd -
    - mkdir build
    - cd build
    - cmake -DPYTHON_INCLUDE_DIR=$HOME/miniconda/include/python3.6m -DPYTHON_LIBRARY=$HOME/miniconda/lib/libpython3.6m.so ..
    # speed up compiling by using up to 4 jobs at any time
    - make -j4

# Run tests
script:
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
